apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend-check
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 626635436469.dkr.ecr.eu-west-2.amazonaws.com/three-tiers-full-nonprod-euw2:backend-latest
        env:
        - name: DATABASE_USER
          value: admin
        - name: DATABASE_PASSWORD
          value: password
        - name: DATABASE_HOST
          value: mongodb
        - name: PORT
          value: "3001"
        ports:
        - containerPort: 3001
