apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: backend-check
spec:
  selector:
    app: frontend
  ports:
  - port: 5000
    targetPort: 80
  type: ClusterIP #LoadBalancer #ClusterIP
