apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: backend-check
  labels:
    app: frontend
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 626635436469.dkr.ecr.eu-west-2.amazonaws.com/prometheus-grafana-nonprod-euw2:frontend-latest
        env:
        - name: VUE_APP_API_URL
          value: http://wbapp.test.dv/api
        ports:
        - containerPort: 80
