apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: backend-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: <your-frontend-image>
        env:
        - name: VUE_APP_API_URL
          value: "http://wbapp.test.dv/api"
        ports:
        - containerPort: 5000
