version: '3.8'
services:
  mongodb:
    build: ./mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    environment:
      DATABASE_HOST: mongodb
      DATABASE_USER: admin
      DATABASE_PASSWORD: password
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    environment:
      VUE_APP_API_URL: "http://localhost:3001"
    ports:
      - "5000:80"
    depends_on:
      - backend
